### ISSUE TITLE
Rename ck-tensorflow:classification-* programs

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-tensorflow#68] opened 2018-06-15 11:50 UTC
`classification-tensorflow` -> `benchmark-tensorflow-python`
`classification-tensorflow-cpp` -> `benchmark-tensorflow-cpp`
`classification-tflite-cpp` -> `benchmark-tflite-cpp`

Because we already have the set of `tensorflow-classification*` programs with similar names but different intention (usage of single image only and for mobile demo).

But it should be done after merging of https://github.com/ctuning/ck-tensorflow/pull/66 to avoid conflicts.

**Comment by gfursin** [comment] 2018-06-15 13:00
We need to check it with @psyhtest  - we thought to keep program names as they are now (unless we update all docs), and maybe create a separate repo for image classification ... Not sure yet what is the best ... The problem is that name "benchmark" is over-abused and doesn't tell much about what the program does ...

**Comment by Chunosov** [comment] 2018-06-18 04:43
OK, agree. May be it was too hasty suggestion. "benchmark" is quite common word, but these programs do just classification.

**Comment by psyhtest** [comment] 2018-06-19 16:05
We have agreed to adopt the following convention: `<task>-<model>-<framework>` for a model-specific program and `<task>-<framework>` for a model-agnostic one (similar to [TDB](https://github.com/tbd-ai/tbd-suite/tree/master/ImageClassification-Inception_v3/TensorFlow)), where `<task>` is "image classification".

So how about:
- `classification-tensorflow` -> `image-classification-tf-py`
- `classification-tensorflow-cpp` -> `image-classification-tf-cpp`
- `classification-tflite-cpp` -> `image-classification-tflite` (is `tflite` cpp-only?)

Similarly, we would use e.g. `image-classification-mobilenets-armcl-opencl`

**Comment by Chunosov** [comment] 2018-06-20 09:06
> is tflite cpp-only?

It seems to be.
There is some `lite.py` module in tflite dir, but I'm not sure if it is TFLite API. It says "TensorFlow Lite tooling helper functionality" and refers primary to some `toco` that should mean 'TensorFlow optimized converter'

**Comment by Chunosov** [comment] 2018-06-20 09:21
Here is the renaming: https://github.com/ctuning/ck-tensorflow/pull/69

**Comment by psyhtest** [comment] 2018-06-20 12:45
We should update at least the following references:
- [x] https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl/blob/master/script/mobilenets-tensorflow/benchmark.py#L72
- [x] https://github.com/dividiti/ck-request-asplos18-mobilenets-armcl-opencl#make-a-sample-run
- [x] https://github.com/ARM-software/ComputeLibrary/issues/431

**Comment by Chunosov** [comment] 2018-06-21 08:32
There are more references corrected here https://github.com/ctuning/ck-tensorflow/pull/71

**Comment by gfursin** [comment] 2018-06-24 10:08
If this is done, we should close it ...

**Closed as completed** 2018-06-25 03:04 UTC
